### ISSUE TITLE
Build on ubuntu fails with missing "android/log.h"

### ISSUE THREAD

**Issue by patthoyts** [BuLogics/libftdi#2]
Following the instructions in the README.build file I have ensured all the suggested packages are installed.  The current head commit (53f9b6d) fails with the following output:

    [  2%] Built target docs
    [  4%] Building C object src/CMakeFiles/ftdi1.dir/ftdi.c.o
    /home/pat/src/ftdi/libftdi/src/ftdi.c:40:25: fatal error: android/log.h: No such file or directory
    compilation terminated.
    src/CMakeFiles/ftdi1.dir/build.make:62: recipe for target 'src/CMakeFiles/ftdi1.dir/ftdi.c.o' failed
    make[2]: *** [src/CMakeFiles/ftdi1.dir/ftdi.c.o] Error 1
    CMakeFiles/Makefile2:156: recipe for target 'src/CMakeFiles/ftdi1.dir/all' failed
    make[1]: *** [src/CMakeFiles/ftdi1.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2

Commit 3e078e1 builds ok but between that commit and the current head are a number of problems with swig errors before we get to the new android header issue.

The cmake output for this build was:

    -- Build type: RelWithDebInfo
    -- Boost version: 1.58.0
    -- Doxygen found.
    -- Generating API documentation with Doxygen
    fatal: No annotated tags can describe '53f9b6dca7364784c99025822b5301f83eacc6ed'.
    However, there were unannotated tags: try --tags.
    -- Detected git snapshot version: unknown
    -- Building libftdi1++
    -- Building python bindings via swig. Will be installed under /usr/local/lib/python2.7/dist-packages
    -- Building ftdi_eeprom
    -- Building example programs.
    -- Building libftdi++ examples.
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   unit_test_framework
    -- Building unit test
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/pat/src/ftdi/libftdi/build

**Comment by gmagee101** [comment]
Pat,

This is a fork of the main libftdi repository, which we are using for development on android

git://developer.intra2net.com/libftdi is the central repository, which should build for ubuntu, but we do not maintain.

Best Regards,
Gabrielle Trotter

**Comment by patthoyts** [comment]
Ah - apologies. I missed that even though it's clearly in the project description.
Thank you for your response.
